#! /bin/sh

cat << 'EOF'
search --no-floppy --fs-uuid --set thumbdrive <fs-uuid>
if [ "${thumbdrive}" ] ; then
  set default="2" # Set boot entry 2 as default (Windows)
else
  set default="0" # Set boot entry 0 as default (Linux)
fi

EOF
